# Generated by Django 4.2.30 on 2026-07-13 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsg', '0002_user_profile_picture_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('scope', models.CharField(choices=[('WARD', 'Ward'), ('PANCHAYAT', 'Panchayat')], default='WARD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='lsg.panchayat')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='lsg.ward')),
            ],
        ),
    ]
