# Generated by Django 4.2.30 on 2026-08-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsg', '0004_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Password Last Changed At'),
        ),
    ]
