# Generated by Django 4.2.30 on 2026-08-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsg', '0005_user_password_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VILLAGER', 'Villager'), ('WARD_MEMBER', 'Ward Member'), ('PANCHAYAT_PRESIDENT', 'Panchayat President')], default='VILLAGER', max_length=20),
        ),
    ]
