# Generated by Django 4.2.30 on 2026-08-01 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsg', '0006_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='documents/', verbose_name='Document File')),
                ('category', models.CharField(choices=[('NOTICE', 'Notice'), ('FORM', 'Form / Application'), ('CIRCULAR', 'Circular'), ('REPORT', 'Report'), ('OTHER', 'Other')], default='NOTICE', max_length=20)),
                ('scope', models.CharField(choices=[('WARD', 'Ward'), ('PANCHAYAT', 'Panchayat')], default='PANCHAYAT', max_length=20)),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Pin to Sidebar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lsg.panchayat')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lsg.ward')),
            ],
        ),
    ]
