# Generated by Django 4.2.30 on 2026-08-03 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsg', '0007_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('EMERGENCY', 'Emergency'), ('HEALTH', 'Health & Sanitation'), ('DEVELOPMENT', 'Development Work'), ('GENERAL', 'General Announcement')], default='GENERAL', max_length=50)),
                ('scope', models.CharField(choices=[('WARD', 'Ward'), ('PANCHAYAT', 'Panchayat')], default='WARD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='lsg.panchayat')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='lsg.ward')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
