# Generated by Django 4.2.30 on 2026-08-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsg', '0008_alert_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
