# Generated by Django 4.2.30 on 2026-08-04 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsg', '0009_alter_alert_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/', verbose_name='Document File')),
                ('category', models.CharField(choices=[('CIRCULAR', 'Official Circular'), ('NOTICE', 'Public Notice'), ('FORM', 'Application Form'), ('REPORT', 'Report & Minutes')], default='CIRCULAR', max_length=50)),
                ('scope', models.CharField(choices=[('WARD', 'Ward'), ('PANCHAYAT', 'Panchayat')], default='WARD', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lsg.panchayat')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lsg.ward')),
            ],
        ),
    ]
