# Generated by Django 4.2.30 on 2026-09-18 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsg', '0010_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('ROADS', 'Roads & Infrastructure'), ('WATER', 'Water Supply'), ('ELECTRICITY', 'Electricity & Streetlights'), ('SANITATION', 'Sanitation & Waste'), ('DRAINAGE', 'Drainage & Sewage'), ('GENERAL', 'General Grievance')], default='GENERAL', max_length=50)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='complaints/', verbose_name='Attachment File')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SOLVED', 'Solved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='lsg.panchayat')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_complaints', to=settings.AUTH_USER_MODEL)),
                ('villager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_complaints', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='lsg.ward')),
            ],
        ),
    ]
